# Generated by Django 4.1 on 2022-09-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_rename_data_puble_film_data_publ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='data_publ',
            new_name='data_puble',
        ),
    ]
