# Generated by Django 4.1 on 2022-09-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_data_publ_film_data_puble'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя режесcера')),
                ('descriptions', models.TextField(blank=True, verbose_name='Биография')),
                ('imag', models.ImageField(upload_to='image/descriptions/%Y')),
            ],
            options={
                'verbose_name': 'Режиссеры',
                'verbose_name_plural': 'Режиссер',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('url', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='film',
            name='url',
            field=models.SlugField(default='film', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='direction',
            field=models.ManyToManyField(related_name='film_direct', to='films.direction', verbose_name='Режиссеры'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='films.genre', verbose_name='Жанры'),
        ),
    ]
