# Generated by Django 4.1 on 2022-09-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_direction_genre_alter_film_options_film_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='descriohions',
            new_name='descriptions',
        ),
    ]
